### Prezto

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

### Custom

export PATH="$HOME/bin:/usr/local/bin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"
export EDITOR='vim'
export HOMEBREW_NO_EMOJI=1
export AWS_ACCESS_KEY_ID=AKIAJP3VWVXDDW7EDT5A
export AWS_DEFAULT_REGION=eu-west-1
export LC_MESSAGES='en_US.UTF-8'
export JAVA_HOME=$(/usr/libexec/java_home)

alias zcat='gzcat'
alias http='python -m SimpleHTTPServer'
alias gitc=gitx

### Tools

# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Travis
[ -f /Users/theo/.travis/travis.sh ] && source /Users/theo/.travis/travis.sh

# Fuzzy finder
source ~/.fzf.zsh
