### Prezto

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

### Custom

unsetopt CORRECT
unsetopt SHARE_HISTORY
unsetopt INC_APPEND_HISTORY
unsetopt AUTO_NAME_DIRS
setopt CLOBBER

export PATH="$HOME/bin:/usr/local/bin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"
export HOMEBREW_NO_EMOJI=1
export AWS_ACCESS_KEY_ID=AKIAIWIB763EXPAUMERA
export AWS_DEFAULT_REGION=eu-west-1
export AWS_AUTO_SCALING_HOME=/usr/local/opt/auto-scaling/libexec
export LC_MESSAGES='en_US.UTF-8'
export JAVA_HOME=$(/usr/libexec/java_home)
export LSCOLORS='fxgxcxdxbxegedabagacad'

alias zcat='gzcat'
alias http='python -m SimpleHTTPServer'
alias gitc=gitx
alias fixup='git commit --fixup $(git log --pretty=format:"%h%d %Creset%s [%cn]" --decorate | peco | cut -d " " -f 1)'
alias bost='al | peco | multi-ssh2'

### Tools

# Bool
export BOOL_HOME="/Users/theo/Documents/Code/bool"
source "$BOOL_HOME/boolrc.sh"

# AWS CLI
source /usr/local/share/zsh/site-functions/_aws

# Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Travis
[ -f /Users/theo/.travis/travis.sh ] && source /Users/theo/.travis/travis.sh

# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"

# rbenv
#eval "$(rbenv init -)"
